### ISSUE TITLE
Python 3 tkinter GUI curve and surface fitter

### ISSUE THREAD

**Issue by zunzun** [Zaab1t/Least-Squares-Fitting#1]
I saw that you have created a tkinter curve fitter on GitHub and thought you might like to see my Python GUI graphical curve fitter and surface fitter, also on github with a BSD license. The matplotlib 3D surface plots of the fitted equations look really cool (my background is in nuclear engineering and industrial radiation physics).

The code uses a linear solver if the equation is linear, and a non-linear Levenberg-Marquardt solver from scipy if the equation is non-linear. It automatically uses scipy's genetic algorithm to produce initial parameter estimates for the non-linear solver.

The URL on github is https://github.com/zunzun/tkInterFit

James Phillips

**Comment by carlbordum** [comment]
Hi @zunzun,
Just checked out your libraries, and I have to say, they're great! You clearly have a much greater understanding in this field. Well done! - let me know if I can help in anyway (probably with more general Python stuff, though).

**Comment by zunzun** [comment]
Thank you kindly for the offer of technical assistance, that is quite the professional courtesy. It is probably safe to close this GitHub issue now.
